### ISSUE TITLE
问一下 async-vendors 有什么作用

### ISSUE THREAD

**Issue by heden9** [lili21/webpack4-demo#1]
不太清楚这个配置有什么作用，好像没看出什么效果

**Comment by lili21** [comment]
如果你有尝试做code splitting的话，比如按路由按需加载。假设你有5个路由，A,B,C,D,E。你就有5个按需加载的模块，async-vendors的作用就是把这5个模块里共用的东西放在一起。

**Comment by heden9** [comment]
我是做了路由的按需加载的，看配置应该是提取异步模块中被引用两次以上的node_modules 中的模块。可是我在打包生成的info里的，并没有看到async-vendors 这个名字。然后我把这个配置注掉了，产出也没有什么变化 (╯﹏╰)

**Comment by lili21** [comment]
说明异步模块里并没有共用的代码

**Comment by heden9** [comment]
是有的，我在两个以上的异步模块中引入了 三方库。虽然他会被自动chunk出来，但是看起来不是 async-vendors 的功劳。因为把他注掉也没有变化。

https://codepen.io/771854332/project/editor/XEPPdo

**Comment by lili21** [comment]
不知道你说的自动chunk出来是什么意思。

另外你用的是`import('iscroll'`)。这个本身就是一个code splitting。`import iscroll from 'iscroll'`

**Comment by heden9** [comment]
啊.....明白啦。感谢大佬😊。
